# == Let's Encrypt
certbot_email: admin@example.org
certbot_renew_cron_hour: 3
certbot_renew_cron_minute: 20
certbot_staging: true


# === Nginx
backend_name: nexus
backend_port: 8081
server_name: nexus.example.org
# Example: server_alias: repo.example.org
server_alias: 


# === Nexus
nexus_autoconfiguration: false
