# === Nexus
nexus_docker_image: sonatype/nexus3:3.63.0
nexus_autoconfiguration: true


# === Nginx
nexus_nginx_docker_image: nginx:latest
nexus_backend_name: nexus
nexus_backend_port_mappings:
  - 8081:8081
  - 8082:8082
  - 8083:8083
  - 8084:8084
nexus_backend_volume_mappings:
  - /srv/nexus/nexus-data:/nexus-data
nexus_server_name: nexus.sys.flatexdegiro.com
# Example: nexus_server_alias: repo.example.org
nexus_server_alias: 


# == Let's Encrypt
nexus_certbot_email: it-cloudops@flatexdegiro.com
nexus_certbot_renew_cron_hour: 3
nexus_certbot_renew_cron_minute: 20
nexus_certbot_staging: true

# === Docker Compose
docker_compose_version: v2.9.0
